//! Audit context helpers for DBFlux.
//!
//! This module provides [`EventOrigin`] and [`AuditContext`] to stamp
//! actor/source metadata and correlation fields onto audit events in a
//! consistent, structured way.
//!
//! ## EventOrigin
//!
//! Maps an emission boundary to its canonical `(actor_type, source_id)` pair.
//! Every boundary (MCP, UI, hook, script, system) has exactly one origin.
//!
//! ## AuditContext
//!
//! Carries session/correlate/connection metadata that applies across a whole
//! operation. A single user action may generate multiple audit events that all
//! share the same `correlation_id` and connection context.

use serde::{Deserialize, Serialize};

use super::types::{EventActorType, EventSourceId};

/// The origin of an audit event — maps a boundary to its canonical
/// `(actor_type, source_id)` pair.
///
/// Use `EventOrigin::mcp()`, `EventOrigin::local()`, etc. to construct.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct EventOrigin {
    /// Actor type that initiates actions from this origin.
    pub actor_type: EventActorType,
    /// Source system that generated the event.
    pub source_id: EventSourceId,
}

impl EventOrigin {
    /// MCP client boundary — used for AI client requests.
    pub fn mcp() -> Self {
        Self {
            actor_type: EventActorType::McpClient,
            source_id: EventSourceId::Mcp,
        }
    }

    /// Local UI boundary — used for user-initiated actions through the DBFlux UI.
    pub fn local() -> Self {
        Self {
            actor_type: EventActorType::User,
            source_id: EventSourceId::Local,
        }
    }

    /// Hook execution boundary — used when a hook script runs.
    pub fn hook() -> Self {
        Self {
            actor_type: EventActorType::Hook,
            source_id: EventSourceId::Hook,
        }
    }

    /// Script execution boundary — used when a Lua/Python/Bash script runs.
    pub fn script() -> Self {
        Self {
            actor_type: EventActorType::Script,
            source_id: EventSourceId::Script,
        }
    }

    /// System boundary — used for application lifecycle events.
    pub fn system() -> Self {
        Self {
            actor_type: EventActorType::System,
            source_id: EventSourceId::System,
        }
    }

    /// App boundary — used when the application acts autonomously.
    pub fn app() -> Self {
        Self {
            actor_type: EventActorType::App,
            source_id: EventSourceId::System,
        }
    }
}

/// Audit context that carries correlation and connection metadata across
/// an operation.
///
/// Multiple audit events generated by a single user action (e.g., authorize
/// + execute) share the same `correlation_id`. Connection-scoped operations
///   (query, hook) carry the connection/profile identifiers.
///
/// # Example
///
/// ```ignore
/// let ctx = AuditContext::default()
///     .with_correlation_id(correlation_id)
///     .with_connection("profile-uuid", "mydb", "postgres");
///
/// event = EventRecord::new(...)
///     .with_action(actions::MCP_AUTHORIZE)
///     .with_origin(ctx.origin)
///     .with_correlation_id(ctx.correlation_id.as_deref().unwrap())
///     // ...
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AuditContext {
    /// Origin of the event (actor_type + source_id).
    pub origin: EventOrigin,
    /// Session ID for the current user session.
    pub session_id: Option<String>,
    /// Correlation ID that links related events across boundaries.
    pub correlation_id: Option<String>,
    /// Connection profile ID if applicable.
    pub connection_id: Option<String>,
    /// Target database name if applicable.
    pub database_name: Option<String>,
    /// Driver identifier (e.g., "postgres", "mongodb").
    pub driver_id: Option<String>,
    /// Type of object affected (e.g., "table", "profile", "hook").
    pub object_type: Option<String>,
    /// ID of the specific object affected.
    pub object_id: Option<String>,
}

impl AuditContext {
    /// Creates a new context with default origin (system).
    pub fn new() -> Self {
        Self::default()
    }

    /// Creates a context with the given origin.
    pub fn with_origin(mut self, origin: EventOrigin) -> Self {
        self.origin = origin;
        self
    }

    /// Sets the session ID.
    pub fn with_session_id(mut self, session_id: impl Into<String>) -> Self {
        self.session_id = Some(session_id.into());
        self
    }

    /// Sets the correlation ID.
    pub fn with_correlation_id(mut self, correlation_id: impl Into<String>) -> Self {
        self.correlation_id = Some(correlation_id.into());
        self
    }

    /// Sets the connection context (connection_id, database_name, driver_id).
    pub fn with_connection(
        mut self,
        connection_id: impl Into<String>,
        database_name: impl Into<String>,
        driver_id: impl Into<String>,
    ) -> Self {
        self.connection_id = Some(connection_id.into());
        self.database_name = Some(database_name.into());
        self.driver_id = Some(driver_id.into());
        self
    }

    /// Sets the connection ID only (when database/driver are unknown).
    pub fn with_connection_id(mut self, connection_id: impl Into<String>) -> Self {
        self.connection_id = Some(connection_id.into());
        self
    }

    /// Sets the object reference (object_type, object_id).
    pub fn with_object(
        mut self,
        object_type: impl Into<String>,
        object_id: impl Into<String>,
    ) -> Self {
        self.object_type = Some(object_type.into());
        self.object_id = Some(object_id.into());
        self
    }

    /// Applies this context's fields onto an existing `EventRecord`.
    ///
    /// This is the primary way to stamp correlation and connection metadata
    /// onto an event in a single call.
    pub fn apply_to(self, event: &mut super::types::EventRecord) {
        event.actor_type = self.origin.actor_type;
        event.source_id = self.origin.source_id;

        if let Some(sid) = self.session_id {
            event.session_id = Some(sid);
        }
        if let Some(cid) = self.correlation_id {
            event.correlation_id = Some(cid);
        }
        if let Some(cid) = self.connection_id {
            event.connection_id = Some(cid);
        }
        if let Some(dn) = self.database_name {
            event.database_name = Some(dn);
        }
        if let Some(did) = self.driver_id {
            event.driver_id = Some(did);
        }
        if let Some(ot) = self.object_type {
            event.object_type = Some(ot);
        }
        if let Some(oid) = self.object_id {
            event.object_id = Some(oid);
        }
    }
}

/// Generates a new correlation ID (UUID v4).
///
/// Call sites that need to correlate multiple events use this to create
/// a shared ID before emitting the first event.
pub fn new_correlation_id() -> String {
    uuid::Uuid::new_v4().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_event_origin_mcp() {
        let origin = EventOrigin::mcp();
        assert_eq!(origin.actor_type, EventActorType::McpClient);
        assert_eq!(origin.source_id, EventSourceId::Mcp);
    }

    #[test]
    fn test_event_origin_local() {
        let origin = EventOrigin::local();
        assert_eq!(origin.actor_type, EventActorType::User);
        assert_eq!(origin.source_id, EventSourceId::Local);
    }

    #[test]
    fn test_audit_context_default() {
        let ctx = AuditContext::default();
        assert_eq!(ctx.origin, EventOrigin::system());
        assert!(ctx.session_id.is_none());
        assert!(ctx.correlation_id.is_none());
    }

    #[test]
    fn test_audit_context_with_connection() {
        let ctx = AuditContext::new()
            .with_correlation_id("corr-123")
            .with_connection("conn-uuid", "mydb", "postgres");

        assert_eq!(ctx.correlation_id, Some("corr-123".to_string()));
        assert_eq!(ctx.connection_id, Some("conn-uuid".to_string()));
        assert_eq!(ctx.database_name, Some("mydb".to_string()));
        assert_eq!(ctx.driver_id, Some("postgres".to_string()));
    }

    #[test]
    fn test_audit_context_apply_to() {
        use super::super::types::{EventCategory, EventOutcome, EventRecord, EventSeverity};

        let ctx = AuditContext::new()
            .with_origin(EventOrigin::mcp())
            .with_correlation_id("corr-abc")
            .with_connection("profile-1", "testdb", "sqlite");

        let mut event = EventRecord::new(
            0,
            EventSeverity::Info,
            EventCategory::Mcp,
            EventOutcome::Success,
        )
        .with_action("some_action")
        .with_summary("test");

        ctx.apply_to(&mut event);

        assert_eq!(event.actor_type, EventActorType::McpClient);
        assert_eq!(event.source_id, EventSourceId::Mcp);
        assert_eq!(event.correlation_id, Some("corr-abc".to_string()));
        assert_eq!(event.connection_id, Some("profile-1".to_string()));
        assert_eq!(event.database_name, Some("testdb".to_string()));
        assert_eq!(event.driver_id, Some("sqlite".to_string()));
    }

    #[test]
    fn test_new_correlation_id() {
        let id1 = new_correlation_id();
        let id2 = new_correlation_id();
        assert_ne!(id1, id2);
        // UUID format check (8-4-4-4-12 = 36 chars)
        assert_eq!(id1.len(), 36);
    }
}
